name: Build and Test

on:
  push:
    branches:
      - main  # Executa o workflow quando houver push na branch main
      - develop
  pull_request:
    branches:
      - main  # Executa o workflow quando houver PR na branch main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Install Dependencies
        run: |
          pwd && ls -lha
          # Instale suas dependências aqui se necessário, por exemplo, CocoaPods ou Carthage
          # pod install ou carthage update

      - name: Build the project
        run: |
          xcodebuild clean build \
            -project "Meu Clima.xcodeproj" \
            -scheme "Meu Clima" \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.6' \
            ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
